services:
  base:
    image: base:latest
    container_name: base
    build: 
      context: .
      dockerfile: ./images/base/Dockerfile
  app:
    image: app:latest
    container_name: app
    build: 
      context: .
      dockerfile: ./images/app/Dockerfile
      args:
        - IMAGE=base:latest
        - PORT=${BACKEND_PORT}
    ports:
      - "8000:${BACKEND_PORT}"
    networks:
      - web-app-network
  web:
    image: web:latest
    container_name: web
    build: 
      context: .
      dockerfile: ./images/web/Dockerfile
      args:
        - IMAGE=base:latest
    env_file:
      - ./.env
    ports:
      - "8008:8501"
    networks:
      - web-app-network
networks:
  web-app-network:
    driver: bridge
